services:
  - type: web
    name: communications-agent
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: ./deploy/communications-agent
    envVars:
      - key: PROJECT_CONNECTION_STRING
        sync: false
      - key: MODEL_DEPLOYMENT_NAME
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: SQL_CS
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM_EMAIL
        sync: false
      - key: USER_DIRECTORY_URL
        sync: false
      - key: SHARED_THREAD_ID
        sync: false
    healthCheckPath: /health
    plan: free